import { Button, VerticalBox, Palette, HorizontalBox } from "std-widgets.slint";

import { Store } from "store.slint";
import {
  NetworkInterfaceSelector, ArtnetDevices, ArtnetDisplay, ArtnetControls 
} from "components/index.slint";

// re-export for the native code
export { Store }

component Title {
  HorizontalBox {
    padding-left: 1.5rem;
    padding-top: 1.25rem;
    padding-bottom: 1.25rem;
    Text {
      text: "Artnet Sender";
      font-size: 2.5rem;
    }
  }
}

export component ArtnetSender inherits Window {
  min-width: 500px;
  min-height: 300px;
  preferred-width: 1920px;
  preferred-height: 1080px;
  title: "Artnet Sender";
  icon: @image-url("../icons/favicon-32x32.png");
  VerticalLayout {
    Title {}
    HorizontalLayout {
      vertical-stretch: 1;
      VerticalLayout {
        NetworkInterfaceSelector {}
        ArtnetDevices {}
      }
      VerticalLayout {
        ArtnetDisplay {}
        ArtnetControls {}
      }
    }
  }
}

export component MyMom inherits Window {
  Text {
    text: "mY mOm!!!";
  }
}